# Generated by Django 4.2.5 on 2024-03-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_usuario_avatar_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='avatar',
        ),
        migrations.AddField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(default=None, upload_to='avatars'),
        ),
    ]
