# Generated by Django 4.2.5 on 2024-03-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0012_remove_alojamiento_imagen_imagen_disponibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='alojamiento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='alojamientos'),
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
    ]
