# Generated by Django 4.2.5 on 2024-03-25 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0014_ciudad_alter_alojamiento_ciudad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='calificacion',
        ),
    ]
