# Generated by Django 4.2.5 on 2024-03-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0015_remove_review_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='ciudades'),
        ),
    ]
