# Generated by Django 4.2.5 on 2024-03-27 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0016_ciudad_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disponibilidad',
        ),
    ]
